### PR TITLE
test project completed!

### PR DESCRIPTION
**Pull request by Syedakhter**

### CODE REVIEW

**Review by TolyMelnikov — COMMENTED** [review]
Syed, looks good ! 
How would you do error handling ? As an example, if you type in "###" for a search string, GitHub's API returns a 402. It would be great if you can wire it up, or just comment/walk me through what the logic would look like. Thanks.

**Comment by Syedakhter** [comment]
I think first we will add some validations in the input that it will only take alphabets and no special characters and numbers. This will save us sending useless api calls to the server. Secondly if we send a string and the api returns error against that then I will display an alert of popup that will show that api call is not successful.

**Comment by TolyMelnikov** [comment]
Numbers are definitely allowed in github usernames (in fact quite a few usernames have them). Where would you wire up the code to check for API response code/error ? If you can update your branch/PR with that logic, that would be great.

**Comment by Syedakhter** [comment]
Logic is implemented and pushed

**Comment by TolyMelnikov** [comment]
Syed, I must be missing something. Please point me to the file/line # in your code where you are handling 402 response being returned from GitHub's API ?

**Comment by Syedakhter** [comment]
It's in main.componetnts.ts file line 36
 if ( posts.total_count > 0 ) {
          this.githubdata = posts
          this.isValid = false;
        } else {
          this.githubdata = [];
          this.isValid = true;
        }

**Comment by TolyMelnikov** [comment]
OK. I'll run your code here in a second. Do you agree that there is a difference between getting 0 results successfully (that search string just didn't match anything) vs getting an actual error from an API. Perhaps the whole API is unreachable and we need to message a user accordingly (please input a different search string vs try again later). How do you do that ?

**Comment by Syedakhter** [comment]
We are not allowing user to enter an invalid character, the only possible response from git-hub will be number of records or zero records if user not exists. BTW we can add a check on response status code, if its not 200 then we can show an error message.

**Pull request closed without merging**
